### PR TITLE
fix: align FDC3 web demo implementation metadata with current behavior

### LINKED ISSUE #1795: FDC3 reference implementation (demo) reports incorrect ImplementationMetadata
The FDC3 reference implementation needs to be updated to report correct ImplementationMetadata. It currently reports:

```
    "implementationMetadata": {
      "provider": "FDC3-Web-Demo",
      "providerVersion": "0.1",
      "fdc3Version": "2.0",
      "optionalFeatures": {
        "DesktopAgentBridging": false,
        "OriginatingAppMetadata": true,
        "UserChannelMembershipAPIs": true
      },
```

The inaccurate fields are:

- providerVersion: should match release version number (about to update to 2.2.2)
- fdc3Version: should be 2.2
- optionalFeatures: OriginatingAppMetadata: It doesn't appear to support this currently, but should!

### PR DESCRIPTION
**Pull request by saschabuehrle**
## Bug
Fixes #1795. The FDC3 for Web demo reported outdated implementation metadata values and incorrectly advertised `OriginatingAppMetadata` support.

## Fix
- Updated demo provider version from `0.1` to `2.2.2`
- Updated reported FDC3 version from `2.0` to `2.2`
- Corrected `optionalFeatures.OriginatingAppMetadata` from `true` to `false` in the FDC3 web implementation metadata payload

These updates align the demo metadata with the current implementation behavior.

Greetings, saschabuehrle

### CODE REVIEW

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts [hunk 1]
```diff
@@ -278,7 +278,7 @@ export class OpenHandler implements MessageHandler {
       fdc3Version: sc.fdc3Version(),
       optionalFeatures: {
         DesktopAgentBridging: false,
-        OriginatingAppMetadata: true,
+        OriginatingAppMetadata: false,
```
Comment (kriswest) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts]: This change should be reverted (my bad)
```suggestion
        OriginatingAppMetadata: true,
```
