### PR TITLE
Fdc3 for web impl get agent refactor

### LINKED ISSUE #1429: Implementation of FDC3 For Web
- [x] Fix Demo (2.0 Conformance)
- [x] Dragging Channel Selectors
- [x] Finish coverage of da-server - two tests failing     
- [x] URL Override Argument (@kriswest )
- [x] IFrame Display None for Intent Resolver

### LINKED ISSUE #1430: Address Session Storage issue in FDC3 for the web for same domain iframes in a parent window
The implementation work for FDC3 for the Web identified a problem with the use of Session Storage for saving instanceId / instanceUuid: where iframes are used to display apps within the parent window (a common use case for FDC3 for the Web) and theey are on the same domain, they share a Session Storage instance and will overwrite each others data. 

An adjustment to the proposed session storage use is needed to ensure that Session Storage for same-domain iframes doesn't collide.

### LINKED ISSUE #1433: Complete implementation of SessionStorage retrieval in FDC3 for the Web implementation
The implementation of Session Storage retrieval and the constraining of methods of re-connecting to the desktop agent is not fully implemented in the FDC3 for the Web project. If stored data is found for the specified appId, then discovery methods should be limited to the previous type used (from the 4 defined, see https://deploy-preview-1191--fdc3.netlify.app/docs/next/api/ref/GetAgent#persisted-connection-data). E.g. if the `FAILOVER` type was found, the failover function should be run immediately, whereas if `PROXY_URL` is found, with an `agentUrl` set, then an iframe should be injected with that URL etc..

Handling of the stored data can be found at: https://github.com/finos/FDC3/blob/13425af354a42de5320a445b80a2534f4354431c/packages/fdc3-get-agent/src/messaging/AbstractWebMessaging.ts#L52-L63
It is currently limited to retrieval of an instanceUuid in 1 of the 4 cases and is not affecting discovery as specified.

The final implementation will also be affected by #1430 which will need to change the structure of the data stored.

### LINKED ISSUE #1445: FDC3 for Web: PrivateChannel event listeners should support null type (all events)
FDC3 for Web currently offers request/response message types for both the new `PrivateChannel.addEventListener` function and the deprecated `PrivateChannel.onAddContextListener`/`onUnsubscribe`/`onDisconnect` functions

The current message schema for `privateChannelAddEventListenerRequest` doesn't currently support registering listeners for all event types, where the API function does (by passing `null` for the type argument):

```ts
addEventListener(type: PrivateChannelEventTypes  | null, handler: EventHandler): Promise<Listener>;
```

### LINKED ISSUE #1468: discoverProxyCandidates example code does not find all candidates correctly
### Area of Issue
 - [ ] App Directory
 - [ ] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Desktop Agent Bridging
 - [ ] Use Cases
 - [x] Other

### Issue Description: 
The sample code for discovering proxy candidates here:

https://fdc3.finos.org/docs/next/api/specs/webConnectionProtocol#12-desktop-agent-discovery

Is not complete. It does not add parents of the opener. These parent could also have openers of course. We actually need a recursive function I think. Something like:

```ts
export function discoverProxyCandidates(windowRef?: WindowProxy): WindowProxy[] {
    const candidates: WindowProxy[] = [];

    return addCandidates(windowRef ?? window, candidates);
}

function addCandidates(window: WindowProxy, candidates: WindowProxy[]): WindowProxy[] {
    candidates.push(window);

    if (window.opener != null) {
        addCandidates(window.opener, candidates);
    }

    if (window.parent != window) {
        addCandidates(window.parent, candidates);
    }

    return candidates;
}
```

### PR DESCRIPTION
**Pull request by kriswest**
## Describe your change

Significant refactor of the fdc3-get-agent package to align it with the Standard and a number of change fdc3-agent-proxy or fdc3-web-impl that were necessitated by the changes.

Changes:
- Refactored Session Storage to use new format as introduced in #1442 
- Session Storage data is used to limit discovery options to those used previously in the session
- The TimeoutLoader was eliminated in favour of timeouts in the individual loading strategies (as some actions in Desktop Agent Proxy interfaces can occur beyond the timeout, e.g. identity validation and UI setup)
- AbstractWebMessaging was eliminated and separation of concerns achieved between fdc3-agent-proxy and fdc3-get-agent. The former only handles the DACP protocol (making it easier to use for other puprposes) while the latter handles all WCP messaging (including WCP6Goodbye) to set-up the message port connection in a browser.
- GetInfo API calls are now handled by the fdc3-agent-proxy with a message exchange, rather than using cached data from identity validation step of the WCP.
- Message exchanges use a constant 10 second timeout, rather than inheriting the discovery timeout - this timeout may need further examination - it should possibly be specified by the Desktop Agent, or just set to a long-ish value (e.g. 30 seconds). However, its worth noting that no FDC3 API calls should require a long value as any long-running tasks are handled via events (e.g. context and intent listening).
- Renamed `BasicDesktopAgent` to `DesktopAgentProxy` to better represent its role.
- Comms iframes must now respond to a hello message from the app, rather than simply firing off a handshake when they load - this ensures that they can handle the UI arguments provided in the hello message (and perhaps one day the FDC3 version requested)
- Private Channel events use the updated schemas from #1446 for consistency (avoids unnecessary translation)
- Corrected pagehide handling to only disconnect if persisted == false
- Added some log messaging for getAgent and set many logs to debug level
- Added  Logging utility to prefix log messages and colourise (where supported). This could later be used to disable debug logging with an argument.
- Typing
  - Reduces the number of `any` types and type overrides in many places - there are others still to address
  - Type imports from BrowserTypes are made specific (rather than importing the whole thing and taking parts of it - as this may produce a smaller module and is easier to maintain) - there are others still to address. 
- Linting
  - Pre-PR reports:
    - fdc3-agent-proxy ✖ 41 problems (41 errors, 0 warnings)
    - fdc3-web-impl ✖ 63 problems (63 errors, 0 warnings)
    - fdc3-get-agent ✖ 25 problems (25 errors, 0 warnings)
    - fdc3-for-web-reference-ui ✖ 7 problems (7 errors, 0 warnings)
    -  demo 42 problems (42 errors, 0 warnings)
  - Post-PR reports:
    - fdc3-agent-proxy ✖ 3 problems (3 errors, 0 warnings)
    - fdc3-web-impl ✖ 23 problems (23 errors, 0 warnings)
    - fdc3-get-agent ✔️ 0 problems (0 errors, 0 warnings)
    - fdc3-for-web-reference-ui ✖ 4 problems (4 errors, 0 warnings)
    - demo ✖ 12 problems (12 errors, 0 warnings)
  - A step in the right direction, but more to do! Some are automatically fixable (double non-null assertions with !!) but I have left these in place as each should be reviewed to see if the assertion can be avoided through better typing or defensive programming.
- Tests
  - Refactored fdc3-get-agent test infrastructure to better represent multiple windows, documents and iframes - previously only single window.document would represent the parent, child and iframes at times and was relying on the `getAgent` implementation considering its own window to be a possible parent and to set up messaging with it 0t this is now prevented
  - Introduced new tests for fdc3-getAgent covering SessionStorage use in detail, as well as a number of cases.
  - Added a variable to enable/disable debug logging for test infrastructure and created many log messages.
- fdc3-for-web-impl and demo
  - Added support for reconnecting instances and adjusted behavior to allow connections from instances that have been forgotten (now issued a new instanceId rather than conneciton rejected) 
  - Corrected a race condition on new connections from iframes

### Related Issue

Addresses a number of issues in addition to working to improve the implementation generally:

resolves #1429
resolves #1430
resolves #1433
resolves #1445
resolves #1468 

## Contributor License Agreement

- [x] I acknowledge that a contributor license agreement is required and that I have one in place or will seek to put one in place ASAP.

## Review Checklist

- [x] **Issue**: If a change was made to the FDC3 Standard, was an issue linked above?
- N/A (working on unreleased implementation) **CHANGELOG**: Is a *CHANGELOG.md* entry included?
- [ ] **API changes**: Does this PR include changes to any of the FDC3 APIs (`DesktopAgent`, `Channel`, `PrivateChannel`, `Listener`, `Bridging`)?
  - [ ] **Docs & Sources**: If yes, were both documentation (/docs) and sources updated?<br/>
        *JSDoc comments on interfaces and types should be matched to the main documentation in /docs*
  - [ ] **Conformance tests**: If yes, are conformance test definitions (/toolbox/fdc3-conformance) still correct and complete?<br/>
        *Conformance test definitions should cover all **required** aspects of an FDC3 Desktop Agent implementation, which are usually marked with a **MUST** keyword, and  optional features (**SHOULD** or **MAY**) where the format of those features is defined*
  - [x] **Schemas**: If yes, were changes applied to the Bridging and FDC3 for Web protocol schemas?<br/>
        *The Web Connection protocol and Desktop Agent Communication Protocol schemas must be able to support all necessary aspects of the Desktop Agent API, while Bridging must support those aspects necessary for Desktop Agents to communicate with each other*
    - [x] If yes, was code generation (`npm run build`) run and the results checked in?<br/>
        *Generated code will be found at `/src/api/BrowserTypes.ts` and/or `/src/bridging/BridgingTypes.ts`*
- [ ] **Context types**: Were new Context type schemas created or modified in this PR?
  - [ ] Were the [field type conventions](https://fdc3.finos.org/docs/context/spec#field-type-conventions) adhered to?
  - [ ] Was the `BaseContext` schema applied via `allOf` (as it is in existing types)?
  - [ ] Was a `title` and `description` provided for all properties defined in the schema?
  - [ ] Was at least one example provided?
  - [ ] Was code generation (`npm run build`) run and the results checked in?<br/>
        *Generated code will be found at `/src/context/ContextTypes.ts`*
- [ ] **Intents**: Were new Intents created in this PR?
  - [ ] Were the [intent name prefixes](https://fdc3.finos.org/docs/intents/spec#intent-name-prefixes) and other [naming conventions & characteristics](https://fdc3.finos.org/docs/intents/spec#naming-conventions) adhered to?
  - [ ] Was the new intent added to the list in the [Intents Overview](https://fdc3.finos.org/docs/intents/spec#standard-intents)?

### CODE REVIEW

File: packages/fdc3-agent-proxy/src/BasicDesktopAgent.ts [hunk 1]
```diff
@@ -13,36 +13,36 @@ import {
...
-    this.handshake = handshake;
+    this.heartbeat = heartbeat;
     this.intents = intents;
     this.channels = channels;
     this.apps = apps;
     this.connectables = connectables;
   }
 
-  async addEventListener(type: FDC3EventTypes | null, handler: EventHandler): Promise<Listener> {
+  addEventListener(type: FDC3EventTypes | null, handler: EventHandler): Promise<Listener> {
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/BasicDesktopAgent.ts:45]: If this function is no longer `async`, should it still be marked as returning a `Promise`? Or are all of the returned values promises?

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts [hunk 2]
```diff
@@ -24,47 +23,57 @@ export class DefaultChannel implements Channel {
...
-    const request: BroadcastRequest = {
-      meta: this.messaging.createMeta(),
-      payload: {
-        channelId: this.id,
-        context,
-      },
-      type: 'broadcastRequest',
-    };
-    await this.messaging.exchange<BroadcastResponse>(request, 'broadcastResponse');
+    const done = await this.messaging.exchange<BroadcastResponse>(
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:26]: Why convert `const request: BroadcastRequest = { ... }` to `{ ... } as BroadcastRequest`? The first one was a safer use of typescript.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts [hunk 3]
```diff
@@ -24,47 +23,57 @@ export class DefaultChannel implements Channel {
...
+        meta: this.messaging.createMeta(),
+        payload: {
+          channelId: this.id,
+          context,
+        },
+        type: 'broadcastRequest',
+      } as BroadcastRequest,
+      'broadcastResponse'
+    );
+    console.log('broadcast done', done);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:37]: If this `console.log` is supposed to be here, please use `console.debug`.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts [hunk 4]
```diff
@@ -24,47 +23,57 @@ export class DefaultChannel implements Channel {
...
-      payload: {
-        channelId: this.id,
-        contextType: contextType ?? null,
-      },
-      type: 'getCurrentContextRequest',
-    };
-
     // first, ensure channel state is up-to-date
-    const response = await this.messaging.exchange<GetCurrentContextResponse>(request, 'getCurrentContextResponse');
+    const response = await this.messaging.exchange<GetCurrentContextResponse>(
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:42]: Why convert `request: GetCurrentContextRequest = { ... }` to `{ ... } as GetCurrentContextRequest`? The former was a safer use of typescript.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts [hunk 5]
```diff
@@ -24,47 +23,57 @@ export class DefaultChannel implements Channel {
...
-      theHandler = handler as ContextHandler;
-    } else if (typeof contextType === 'string') {
-      theContextType = contextType;
-      theHandler = handler as ContextHandler;
-    } else {
+      theHandler = handler;
+    } else if (typeof contextTypeOrHandler === 'string' && handler) {
+      theContextType = contextTypeOrHandler;
+      theHandler = handler;
+    } else if (contextTypeOrHandler) {
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:70]: So, if someone calls `.addContextListener("fdc3.instrument")`, the context type will get null'd out because I didn't provide a handler? Am I reading that right?

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 6]
```diff
@@ -93,8 +113,14 @@ export class DefaultChannelSupport implements ChannelSupport {
...
     };
     const response = await this.messaging.exchange<GetOrCreateChannelResponse>(request, 'getOrCreateChannelResponse');
-
-    return new DefaultChannel(this.messaging, id, 'app', response.payload.channel?.displayMetadata!!);
+    //handle successful responses - errors will already have been thrown by exchange above
+    if (response.payload.channel) {
+      const out = new DefaultChannel(this.messaging, id, 'app', response.payload.channel.displayMetadata);
+      return out;
+    } else {
+      console.error('Invalid response from Desktop Agent to getUserChannelsRequest!', response);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:121]: Doesn't `console.error` also throw an error? Wouldn't that mean that the next line is both redundant and unreachable?

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 7]
```diff
@@ -107,8 +133,12 @@ export class DefaultChannelSupport implements ChannelSupport {
       request,
       'createPrivateChannelResponse'
     );
-
-    return new DefaultPrivateChannel(this.messaging, response.payload?.privateChannel?.id!!);
+    if (response.payload.privateChannel) {
+      return new DefaultPrivateChannel(this.messaging, response.payload.privateChannel.id);
+    } else {
+      console.error('Invalid response from Desktop Agent to getUserChannelsRequest!', response);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:139]: ditto

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 8]
```diff
@@ -56,30 +64,42 @@ export class DefaultChannelSupport implements ChannelSupport {
...
+        response.payload
+      );
       return null;
     }
   }
 
   async getUserChannels(): Promise<Channel[]> {
-    if (!this.userChannels) {
-      const request: GetUserChannelsRequest = {
+    const response = await this.messaging.exchange<GetUserChannelsResponse>(
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:88]: Is it possible to have a `const request: GetUserChannelsRequest`, for better type safety?

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 9]
```diff
@@ -132,28 +161,41 @@ export class DefaultChannelSupport implements ChannelSupport {
       },
     };
     await this.messaging.exchange<JoinUserChannelResponse>(request, 'joinUserChannelResponse');
-
-    this.channelSelector.updateChannel(id, this.userChannels ?? []);
-
-    for (const l of this.followingListeners) {
+    this.channelSelector.updateChannel(id, this.userChannels);
+    for (const l of this.userChannelListeners) {
       await l.changeChannel(new DefaultChannel(this.messaging, id, 'user'));
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:166]: It looks like there are 2 separate patterns for changing all the channels. 
Line 152: `this.userChannelListeners.forEach(l => l.changeChannel(null));`
Line 166:
```
for (const l of this.userChannelListeners) {
  await l.changeChannel(new DefaultChannel(this.messaging, id, 'user'));
}
```

Should they both use the same pattern?

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts [hunk 10]
```diff
@@ -1,54 +1,115 @@
...
-    const notificationMessage = {
+  async register(): Promise<void> {
+    const subscribeMessage: Y = {
       meta: this.messaging.createMeta(),
-      payload: this.id ? { listenerUUID: this.id } : { ...this.payloadDetails },
-      type: requestType,
-    };
+      payload: this.subscriptionPayload,
+      type: this.subscribeRequestType,
+    } as Y;
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:102]: Is the `as Y` necessary?

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts [hunk 11]
```diff
@@ -1,54 +1,115 @@
...
-    return response?.payload?.listenerUUID ?? null;
-  }
+    const response = await this.messaging.exchange<SubscriptionResponse>(subscribeMessage, this.subscribeResponseType);
+    this.id = response?.payload?.listenerUUID ?? null;
 
-  async unsubscribe(): Promise<void> {
     if (!this.id) {
-      throw new Error("Can't unsubscribe from a listener that has not been registered.");
+      console.error(
+        "The Desktop Agent's response did not include a listenerUUID, which will mean this listener can't be removed!",
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:109]: Excellent error message

File: packages/fdc3-agent-proxy/src/listeners/HeartbeatListener.ts [hunk 12]
```diff
@@ -26,6 +30,7 @@ export class HeartbeatListener implements RegisterableListener {
         heartbeatEventUuid: (_m as HeartbeatEvent).meta.eventUuid,
       },
     } as HeartbeatAcknowledgementRequest);
+    //console.log("Heartbeat acknowledged")
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/listeners/HeartbeatListener.ts:33]: Is this supposed to be here? Either delete or add a comment indicating that it was left intentionally, like 
```
// Uncomment when debugging heartbeat messages
```

File: packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts [hunk 13]
```diff
@@ -1,165 +1,81 @@
...
           resolve(m);
         },
-        register: async () => {
-          this.register(listener);
-        },
-        unsubscribe: async () => {
-          this.unregister(id);
-        },
-      };
+      } as RegisterableListener;
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts:39]: Is `as RegisterableListener` necessary?

File: packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts [hunk 14]
```diff
@@ -180,14 +178,17 @@ Given('{string} pipes context to {string}', function (this: CustomWorld, context
 
 When('messaging receives {string}', function (this: CustomWorld, field: string) {
   const message = handleResolve(field, this);
-  this.log(`Sending: ${JSON.stringify(message)}`);
-  this.messaging!!.receive(message, this.log);
+  //TODO: restore this
+  //this.log(`Sending: ${JSON.stringify(message)}`);
+  console.log(`Sending: `, message);
+
+  this.messaging!.receive(message, console.log); //this.log);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts:185]: Flagging this section, since it looks like it's still a WIP

File: packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts [hunk 15]
```diff
@@ -180,14 +178,17 @@ Given('{string} pipes context to {string}', function (this: CustomWorld, context
...
 });
 
 Then('messaging will have posts', function (this: CustomWorld, dt: DataTable) {
   // just take the last few posts and match those
   const matching = dt.rows().length;
-  var toUse = this.messaging?.allPosts!;
+  let toUse = this.messaging!.allPosts!;
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts:191]: Are the `!` here necessary?

File: packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts [hunk 16]
```diff
@@ -1,30 +1,53 @@
...
+  AddIntentListenerResponse,
+  AppRequestMessage,
+  PrivateChannelAddEventListenerRequest,
+  PrivateChannelAddEventListenerResponse,
+} from '@kite9/fdc3-schema/generated/api/BrowserTypes';
 import { AutomaticResponse, TestMessaging } from '../TestMessaging';
 import { createResponseMeta } from './support';
 import { v4 as uuidv4 } from 'uuid';
 
+type requests =
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts:16]: Would you mind pascal casing your types? It'd be consistent with the other types that have been defined. like `type SupportedListenerRequests = ...`

File: packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts [hunk 17]
```diff
@@ -1,30 +1,53 @@
...
-      t == 'privateChannelAddContextListenerRequest' ||
+      t == 'addEventListenerRequest' ||
       t == 'privateChannelAddEventListenerRequest'
     );
   }
 
-  action(input: object, m: TestMessaging) {
-    const out = this.createResponse(input);
+  action(input: AppRequestMessage, m: TestMessaging) {
+    const out = this.createResponse(input as requests);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts:38]: Why the `as requests` here? Does `AppRequestMessage` not overlap with the list of possible listener requests?

File: packages/fdc3-agent-proxy/test/support/responses/UnsubscribeListeners.ts [hunk 18]
```diff
@@ -1,24 +1,50 @@
...
+  IntentListenerUnsubscribeRequest,
+  IntentListenerUnsubscribeResponse,
+  PrivateChannelUnsubscribeEventListenerRequest,
+  PrivateChannelUnsubscribeEventListenerResponse,
+} from '@kite9/fdc3-schema/generated/api/BrowserTypes';
 import { AutomaticResponse, TestMessaging } from '../TestMessaging';
 import { createResponseMeta } from './support';
+import { EventListenerUnsubscribeResponse } from '@kite9/fdc3-schema/dist/generated/api/BrowserTypes';
 
+type requests =
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/test/support/responses/UnsubscribeListeners.ts:14]: See comments on ./RegisterListeners.ts

File: packages/fdc3-context/generated/context/ContextTypes.ts [hunk 19]
```diff
@@ -2139,1013 +2129,910 @@ export interface Valuation {
...
+        { json: "dataUri", js: "dataUri", typ: "" },
+        { json: "name", js: "name", typ: "" },
+    ], "any"),
+    "Instrument": o([
+        { json: "id", js: "id", typ: r("FluffyInstrumentIdentifiers") },
+        { json: "market", js: "market", typ: u(undefined, r("PurpleMarket")) },
+        { json: "name", js: "name", typ: u(undefined, "") },
+        { json: "type", js: "type", typ: r("PurpleInteractionType") },
+    ], "any"),
+    "FluffyInstrumentIdentifiers": o([
```
Comment (julianna-ciq) [inline packages/fdc3-context/generated/context/ContextTypes.ts:2755]: Is "FluffyInstrument" a real thing?

**Review by julianna-ciq — COMMENTED** [review]
Reviewing files 1-50/132

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts (hunk 2 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:26]: Appears to be a bad merge. Both you and I have fixed that, then it's gotten reverted when I merged the prettier PR. I'll have to comb through and look for any similar reversions (sigh)

File: packages/fdc3-agent-proxy/src/BasicDesktopAgent.ts (hunk 1 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/BasicDesktopAgent.ts:45]: Yes its passing through the promise from `DefaultChannelSupport.addChannelChangedEventHandler`.

All returned values are indeed promises - although the throw on line 50 should probably be a `Promise.reject` now, although I doubt it would make much difference.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts (hunk 3 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:37]: again it came back with that bad merge 🤦

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts (hunk 5 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:70]: This is handling the old deprecated addContextListener signature here: https://github.com/finos/FDC3/blob/d5aab3f3cc1d98598cae9d6cdd063b36e509bcdf/src/api/DesktopAgent.ts#L554-L558

It still exists until fdc3 3.0 when it will be terminated (with prejudice). Untilt hen if they only provide one argument then we have to assume its the handler function and that it should be applied to all context types (as if the first arg was null and the second was the handler).

What could make this better is checking that the first argument is a function (which I'll do) - as this call makes no sense without a handler function being passed:
`} else if (typeof contextTypeOrHandler === "function") {`

Hence if they call `.addContextListener("fdc3.instrument")` it'll reject with the error message.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 8 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:88]: Absolutely, probably another reversion, glad you're looking for them.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 6 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:121]: nope, it just prints to stderr so you need to log before throwing (as a log message after throwing is unreachable).

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 7 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:139]: nope

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 9 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:166]: Yes they should, fixing that on the for loop style (as I find it slightly easier to read than forEach).

File: packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts (hunk 13 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts:39]: It was due to the lack of the register and unregister functions, which don't get used here... I've put them back to remove this. However, I do find it architecturally confusing that both the listeners and AbstractMessaging have `register` and `unsubsubscribe`/`unregister` functions... It should probably be the responsibility of one or the other rather than either... Generally, the listeners own functions are just grabbing a reference to the Messaging instance and calling its register function anyway.

File: packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts (hunk 14 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts:185]: Cleaned up, looks to be in use in quite a few tests.

File: packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts (hunk 15 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/test/step-definitions/channels.steps.ts:191]: Apparently so... The reference is set up in CustomWorld:

https://github.com/finos/FDC3/blob/7b330ac75f627b3c1faddba7f753547b08792b0c/packages/fdc3-agent-proxy/test/world/index.ts#L6

Then populated by a step that is used in the background for each test file:


https://github.com/finos/FDC3/blob/7b330ac75f627b3c1faddba7f753547b08792b0c/packages/fdc3-agent-proxy/test/step-definitions/generic.steps.ts#L15-L19)

If you can figure out something better I'll happily drop the !

File: packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts (hunk 17 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/test/support/responses/RegisterListeners.ts:38]: `AppRequestMessage` is indeed a superset, but I typed `createResponse` using `Requests` so it'll error out in the build without the override. I tried to improve on this by making AutomaticResponse a generic using the request types, but afterwards, you can't type a mixed array of them easily as we do here:
https://github.com/finos/FDC3/blob/7b330ac75f627b3c1faddba7f753547b08792b0c/packages/fdc3-agent-proxy/test/support/TestMessaging.ts#L113-L114

File: packages/fdc3-agent-proxy/test/support/responses/UnsubscribeListeners.ts (hunk 18 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/test/support/responses/UnsubscribeListeners.ts:14]: done

File: packages/fdc3-context/generated/context/ContextTypes.ts (hunk 19 above)
Comment (kriswest) [reply packages/fdc3-context/generated/context/ContextTypes.ts:2755]: Its something that Quicktype creates when it has name conflicts. It creates type to represent properties of other types - their names don't really matter as they are just part of the top-level types structure. However, I do wish it didn't export them (assuming they can still be used as part of another exported tye) as they are not safe to use (a later change can trigger them getting generated with a different name).

Hmm, it might be worth post-processing the output with TSMorph and stopping them getting exported...

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts (hunk 11 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:109]: 🙇

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts (hunk 10 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:102]: Apparently so - I don't understand why. The error message is: 

> 'Y' could be instantiated with an arbitrary type which could be unrelated to '{ meta: Y["meta"]; payload: Y["payload"]; type: Y["type"]; }'

This happens even if I type the individual properties: meta, payload, type):

```ts
const subscribeMessage: Y = {
      meta: this.messaging.createMeta() as Y['meta'],
      payload: this.subscriptionPayload as Y['payload'],
      type: this.subscribeRequestType as Y['type'],
    };
```

So there clearly something about TypeScript that I don't understand here. If you can figure it out @julianna-ciq you'd be teaching me something ;-)

File: packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts [hunk 20]
```diff
@@ -1,165 +1,91 @@
...
-          this.register(listener);
+          this.register(l);
         },
         unsubscribe: async () => {
           this.unregister(id);
         },
       };
 
-      listener.register();
+      this.register(l);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts:51]: Just flagging this line because `this` scoping is a common pain point in javascript. I think `this` refers to the promise at this point, but could refer to the class...

Either way, please double check this line to make absolutely certain you want `this.register(l)` instead of `l.register`

File: packages/fdc3-get-agent/test/support/FrameTypes.ts [hunk 21]
```diff
@@ -1,80 +1,94 @@
...
       type: 'message',
-      data: {
-        type: FDC3_USER_INTERFACE_HELLO_TYPE,
-        payload: {
-          initialCSS: {
-            width: '100px',
-          },
-        },
-      } as Fdc3UserInterfaceHello,
+      data: msg,
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/FrameTypes.ts:74]: Is it possible to do something like this:

```ts
const event: Event = {
  type: "message",
  data: msg,
  origin: CHANNEL_SELECTOR_URL,
  source,
  ports: [connection.port1]
};
parent.dispatchEvent(event);
```

Just to avoid doing `as unknown as Event`

File: packages/fdc3-get-agent/test/support/FrameTypes.ts [hunk 22]
```diff
@@ -89,37 +103,40 @@ export function handleChannelSelectorComms(
...
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/FrameTypes.ts:122]: ditto

File: packages/fdc3-get-agent/test/support/MockDocument.ts [hunk 23]
```diff
@@ -6,24 +6,36 @@ export class MockDocument {
...
+      //n.b. variables are set on the parent window to link each iframe in order to allow use as source in
+      // postMessages from them - these are set in the MockIframe.setAttribute function
+
       this.iframes.push(mw);
-      return mw as any;
+
+      return mw as unknown as HTMLElement;
     } else {
-      return new MockElement(tag) as any;
+      return new MockElement(tag) as unknown as HTMLElement;
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/MockDocument.ts:33]: It would be better if MockIFrame and MockElement were of type HTMLElement, so that you don't need to have `as unknown as HTMLElement` all over the place. Like, you might have to do it in the MockIFrame and MockElement class, but at least you'd only have to do it once.

File: packages/fdc3-get-agent/test/support/MockDocument.ts [hunk 24]
```diff
@@ -6,24 +6,36 @@ export class MockDocument {
...
     }
   }
 
-  getElementById(_id: string): HTMLElement | null {
-    return new MockElement('div') as any;
+  getElementById(/*_id: string*/): HTMLElement | null {
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/MockDocument.ts:37]: Instead of commenting out the argument, should it just be removed?

Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/MockDocument.ts:37]: This method only returns type `HTMLElement`, and would never return `null`. Should we continue to have `| null` in the type definition if null can't ever be returned?

File: packages/fdc3-get-agent/test/support/TestServerContext.ts [hunk 25]
```diff
@@ -46,46 +50,65 @@ export class TestServerContext implements ServerContext<ConnectionDetails> {
...
+      const ni = this.nextInstanceId++;
+      if (appId.includes('missing')) {
+        throw new Error(OpenError.AppNotFound);
+      } else {
+        const mc = new MessageChannel();
+        const internalPort = mc.port1;
+        const externalPort = mc.port2;
+
+        //   internalPort.name = 'internalPort-' + ni;
+        //   externalPort.name = 'externalPort-' + ni;
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/TestServerContext.ts:90]: Do these commented-out lines need to stay?

**Review by julianna-ciq — COMMENTED** [review]
Reviewing files 51 - 100 / 134

**Comment by kriswest** [comment]
If I take it out only one test is affected which is looking for that message - another version of the same test doesn't check for it and passes. Hence, I think the test just needed adjusting.

We _may_ need a further test to make sure intents can be successfully raised and results retrieved if anything breaks after this, but I'm not expecting anything to break.

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts [hunk 26]
```diff
@@ -2,20 +2,27 @@ import { IntentHandler, IntentResult, AppIdentifier } from '@kite9/fdc3-standard
...
+      messaging,
+      { intent },
+      action,
+      'addIntentListenerRequest',
+      'addIntentListenerResponse',
+      'intentListenerUnsubscribeRequest',
+      'intentListenerUnsubscribeResponse'
+    );
     this.intent = intent;
   }
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts:28]: If I take it out only one test is affected which is looking for that message - another version of the same test doesn't check for it and passes. Hence, I think the test just needed adjusting.

We _may_ need a further test to make sure intents can be successfully raised and results retrieved if anything breaks after this, but I'm not expecting anything to break.

File: packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts [hunk 27]
```diff
@@ -1,165 +1,81 @@
...
+import { AgentResponseMessage, AppRequestMessage } from '@kite9/fdc3-schema/generated/api/BrowserTypes';
 
 export abstract class AbstractMessaging implements Messaging {
-  private readonly options: GetAgentParams;
-  private readonly connectionAttemptUuid: string;
-  private readonly timeout: number;
-  private readonly actualUrl: string;
-  private appId: AppIdentifier | null = null;
-  private implementationMetadata: ImplementationMetadata | null = null;
+  // private implementationMetadata: ImplementationMetadata;
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts]: nope

File: packages/fdc3-get-agent/src/messaging/MessagePortMessaging.ts [hunk 28]
```diff
@@ -38,36 +48,40 @@ export class MessagePortMessaging extends AbstractWebMessaging {
     return uuidv4();
   }
 
-  async post(message: object): Promise<void> {
+  post(message: object): Promise<void> {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/messaging/MessagePortMessaging.ts]: Only that it was manually returning a promise, meannig it didn't need to be marked async. I prefer your suggestion however, so we can lose the line with that manual promise return

[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/messaging/MessagePortMessaging.ts]: Yeah, working on that. Need to unpick one place where there is an odd message being passed to post (agent message but sent from client-side - doesn't look right).

Think I got this sorted.

File: packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts [hunk 29]
```diff
@@ -66,27 +86,40 @@ export abstract class AbstractUIComponent implements Connectable {
...
         fdc3Version: FDC3_VERSION,
       },
     };
-    port.postMessage(handshake);
+    port.postMessage(message);
   }
 
   private awaitHello(): Promise<MessagePort> {
-    return new Promise((resolve, _reject) => {
+    return new Promise((resolve /*, _reject*/) => {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts]: 👍

File: packages/fdc3-get-agent/src/ui/DefaultDesktopAgentChannelSelector.ts [hunk 30]
```diff
@@ -31,21 +35,20 @@ export class DefaultDesktopAgentChannelSelector extends AbstractUIComponent impl
...
             id: ch.id,
+            type: 'user',
             displayMetadata: ch.displayMetadata,
           };
         }),
       },
     };
-    // also send to the iframe
-    this.port?.postMessage(message);
+    this.port!.postMessage(message);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/DefaultDesktopAgentChannelSelector.ts]: Have swapped it for a `?` (as used in DefaultDesktopAgentIntentResolver.ts) - the port is allowed to be null and gets set during its lifecycle.

File: packages/fdc3-get-agent/src/ui/DefaultDesktopAgentIntentResolver.ts [hunk 31]
```diff
@@ -39,19 +45,17 @@ export class DefaultDesktopAgentIntentResolver extends AbstractUIComponent imple
   }
 
   async chooseIntent(appIntents: AppIntent[], context: Context): Promise<IntentResolutionChoice | void> {
-    const out = new Promise<IntentResolutionChoice | void>((resolve, _reject) => {
+    const out = new Promise<IntentResolutionChoice | void>((resolve /*, _reject*/) => {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/DefaultDesktopAgentIntentResolver.ts]: 👍

File: packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts (hunk 20 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/messaging/AbstractMessaging.ts:48]: We're outside the promise and inside the top-level of the `waitFor` implementation here, so should be correct. Soooo many tests would fail if not.

The `register` and `unsubscribe` inside of the waitFor implementation could have a bad this... but then they are not being used directly AFAIK. Hmm, no they don't or typescript would be complaining that Promise doesn't have a register function - all is ok here.

File: packages/fdc3-get-agent/test/support/FrameTypes.ts (hunk 21 above)
Comment (kriswest) [reply packages/fdc3-get-agent/test/support/FrameTypes.ts:75]: This one is a pig. We can mock event, but that doesn't have the `data` property. The alternative is `MessageEvent`, which has a load of other properties we don't supply and doesn't like MockWindow as source.  Basically, anything else I've tried ends up needing at least as many overrides than this.

Best I've managed is:
```ts
const event: Event = new MessageEvent("message",
      {
        data: msg,
        origin: CHANNEL_SELECTOR_URL,
        source: source as unknown as MessageEventSource,
        ports: [connection.port1]
      }
    );
```

which isn't really any better.

File: packages/fdc3-get-agent/test/support/FrameTypes.ts (hunk 22 above)
Comment (kriswest) [reply packages/fdc3-get-agent/test/support/FrameTypes.ts:124]: see above response

File: packages/fdc3-get-agent/test/support/MockDocument.ts (hunk 24 above)
Comment (kriswest) [reply packages/fdc3-get-agent/test/support/MockDocument.ts:37]: As the thing being mocked has that typing is it better to stay true to that, even if the Mock behaves differently?

File: packages/fdc3-get-agent/test/support/TestServerContext.ts (hunk 25 above)
Comment (kriswest) [reply packages/fdc3-get-agent/test/support/TestServerContext.ts]: nope

**Comment by julianna-ciq** [comment]
Doesn’t that mean there’s no tests for returning null? I think it might be better to adjust the function to return null if the id is something like “does-not-exist” or equivalent
________________________________
From: Kris West ***@***.***>
Sent: Monday, December 16, 2024 12:55:58 PM
To: finos/FDC3 ***@***.***>
Cc: Julianna Langston ***@***.***>; Mention ***@***.***>
Subject: [Ext] Re: [finos/FDC3] Fdc3 for web impl get agent refactor (PR #1466)


@kriswest commented on this pull request.

________________________________

In packages/fdc3-get-agent/test/support/MockDocument.ts<https://github.com/finos/FDC3/pull/1466#discussion_r1887265063>:

>      }
   }

-  getElementById(_id: string): HTMLElement | null {
-    return new MockElement('div') as any;
+  getElementById(/*_id: string*/): HTMLElement | null {


As the thing being mocked has that typing is it better to stay true to that, even if the Mock behaves differently?

**Comment by kriswest** [comment]
> Doesn’t that mean there’s no tests for returning null? I think it might be better to adjust the function to return null if the id is something like “does-not-exist” or equivalent

That would be more complete yes, but thats not the thing under test. The only place we actually use the function is the removal of an old iframe in HelloHandler (which would only happen in a very rare case).

File: packages/fdc3-get-agent/src/strategies/FailoverHandler.ts [hunk 32]
```diff
@@ -0,0 +1,131 @@
...
+  identityValidationHandler?: IdentityValidationHandler;
+
+  /**
+   * This is a variation of the PostMessageLoader used for handling failover.
+   * If the failover returns a WindowProxy this is used to create a Desktop
+   * Agent Proxy. If a DesktopAgent is returned directly it is passed through.
+   *
+   */
+  async handleFailover(): Promise<DesktopAgentSelection> {
+    try {
```
Comment (robmoffat) [inline packages/fdc3-get-agent/src/strategies/FailoverHandler.ts:45]: this function should be refactored into smaller chunks.

File: toolbox/fdc3-for-web/demo/src/client/apps/app6.ts [hunk 33]
```diff
@@ -13,7 +13,11 @@ getAgent().then(async fdc3 => {
...
 
-  log!!.textContent = `Got resolution: ${JSON.stringify(reso)}`;
-  const result = await reso.getResult();
-  log!!.textContent += `Got result: ${JSON.stringify(result)}`;
+  if (log) {
+    log.textContent = `Got resolution: ${JSON.stringify(reso)}`;
+    const result = await reso.getResult();
+    log.textContent += `Got result: ${JSON.stringify(result)}`;
+  } else {
+    console.error("Unable to load resolution as the log element didn't exist!");
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/demo/src/client/apps/app6.ts:21]: I guess this is a stylistic choice, but I would always prefer to use ! over if() in this scenario, since the log element will always be set.  Adding the error() is just noise that will never get called.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts [hunk 34]
```diff
@@ -95,35 +101,41 @@ export class HeartbeatHandler implements MessageHandler {
...
       const app = sc.getInstanceDetails(from);
       if (app) {
-        this.lastHeartbeats.set(app.instanceId!!, new Date().getTime());
+        this.lastHeartbeats.set(app.instanceId, new Date().getTime());
       }
     }
 
-    if (msg.type == 'WCP5Shutdown') {
+    if (msg.type == 'WCP6Goodbye') {
       const app = sc.getInstanceDetails(from);
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:121]: this is no longer tested

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts [hunk 35]
```diff
@@ -97,29 +111,38 @@ export class OpenHandler implements MessageHandler {
...
-            return this.getAppMetadata(msg as GetAppMetadataRequest, sc, from);
+        try {
+          if (isOpenRequest(msg)) {
+            return this.open(msg, sc, from);
+          } else if (isFindInstancesRequest(msg)) {
+            return this.findInstances(msg, sc, from);
+          } else if (isGetAppMetadataRequest(msg)) {
+            return this.getAppMetadata(msg, sc, from);
+          } else if (isGetInfoRequest(msg)) {
+            return this.getInfo(msg, sc, from);
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts:136]: this line isn't getting tested.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts [hunk 36]
```diff
@@ -223,71 +248,86 @@ export class OpenHandler implements MessageHandler {
...
       const uuid = await sc.open(source.appId);
       this.pending.set(uuid, new PendingApp(sc, arg0, context, from, this.timeoutMs));
-    } catch (e: any) {
-      errorResponse(sc, arg0, from, e.message, 'openResponse');
+    } catch (e) {
+      errorResponse(sc, arg0, from, (e as Error).message ?? e, 'openResponse');
     }
   }
 
+  async getInfo(arg0: GetInfoRequest, sc: ServerContext<AppRegistration>, from: FullAppIdentifier): Promise<void> {
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts:263]: ... so this never gets called.

**Review by robmoffat — CHANGES_REQUESTED** [review]
first look from me

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 37]
```diff
@@ -107,8 +131,12 @@ export class DefaultChannelSupport implements ChannelSupport {
       request,
       'createPrivateChannelResponse'
     );
-
-    return new DefaultPrivateChannel(this.messaging, response.payload?.privateChannel?.id!!);
+    if (response.payload.privateChannel) {
```
[the remark this answers is not in the document]
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:134]: ok, my other comment got lost, so re-creating it.

Problem is typescript is less discriminatory than JSON schema.  In the schema, if error is set then channel isn't and vice-versa.  If we get to this line, we know error wasn't set, so channel must be.

Therefore we have to decide:
  - If we assume the primacy of JSON schema, we should probably validate the message types in AbstractMessaging using @Roaders new functions and ! out the typescript error, or
  - if we say typescript is the golden source of truth, we need to add tests for all these mutant variations of JSON messages that would come through. 

Personally I think we should go with the former since we have those functions now.

File: packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts [hunk 38]
```diff
@@ -55,10 +60,45 @@ export class DefaultAppSupport implements AppSupport {
...
+    const out = await this.messaging.exchange<GetInfoResponse>(
+      request,
+      'getInfoResponse',
+      'timed out waiting for getInfo response!'
+    );
+    if (out.payload.implementationMetadata) {
+      return out.payload.implementationMetadata;
+    } else {
+      //should never happen as an error returned will be thrown
+      const unknownImpl: ImplementationMetadata = {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts:91]: There are no exceptions defined in the API for that eventuality...

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 39]
```diff
@@ -107,8 +131,12 @@ export class DefaultChannelSupport implements ChannelSupport {
...
+      return new DefaultPrivateChannel(this.messaging, response.payload.privateChannel.id);
+    } else {
+      console.error('Invalid response from Desktop Agent to getUserChannelsRequest!', response);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:137]: wrong function name in the error message is all.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:134]: > The exchange function is testing for an error, and if that's not provided, the channel should be set, shouldn't it?

It should be, but thats relying on 3rd party code being implemented exactly correctly. If a DA developer fails to set either the error or payload elements correctly then they end up in the else clause and get both a specified error and log message they can hunt for. The types allow that as you could return either error or privateChannel so both end up optional.

> but since it's not reachable I don't think we can write one without passing in invalid JSON?

It is reachable with an implementation error in 3rd party code that may not have been written yet.

> Your JSON schema precludes this line of code from being reached?

Schema does, but types don't. Its just a defensive pattern that will better handle errors in 3rd party code.

> Perhaps a better way around this would be to make sure that the exchange function validates the JSON that comes back.

It would be possible to move it there, but either exchange will get much bigger, or it will need to start running validations on every response from a variety of schemas. Thats likely to affect performance at runtime. Whereas these checks on responses are light and easy to understand. I know you're not keen on the if/else statements due to test coverage - there's probably a way to write a general purpose validation function (perhaps not full schema validation, but the presence of a key property) to sort that out. That would look something like:

```ts
async createPrivateChannel(): Promise<PrivateChannel> {
    const request: CreatePrivateChannelRequest = {
      meta: this.messaging.createMeta(),
      type: 'createPrivateChannelRequest',
      payload: {},
    };
    const response = await this.messaging.exchange<CreatePrivateChannelResponse>(
      request,
      'createPrivateChannelResponse'
    );

    throwIfUndefined(response.payload.privateChannel, 'Invalid response from Desktop Agent to createPrivateChannel!',response,ChannelError.CreationFailed);
    
    return new DefaultPrivateChannel(this.messaging, response.payload.privateChannel!.id);
  }
```

File: packages/fdc3-agent-proxy/test/features/private-channels-deprecated.feature [hunk 40]
```diff
@@ -37,7 +37,7 @@ Feature: Basic Private Channels Support
     And I call "{theListener}" with "unsubscribe"
     Then messaging will have posts
       | type                                          | payload.listenerType | payload.privateChannelId | payload.listenerUUID | matches_type                                  |
-      | privateChannelAddEventListenerRequest         | onUnsubscribe        | {privateChannel.id}      | {null}               | privateChannelAddEventListenerRequest         |
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/test/features/private-channels-deprecated.feature:40]: I don't think so: 1) Checking the output wouldn't affect the test coverage on the test result, 2) this test covers the addition of a listener for the unsubscribe event (where the event type name changed recently in #1459), rather than calling `aContextListener.unsubscribe()` or `anEventListner.unsubscribe()`.

Nevertheless, I'll have a look for the untested call and rectify...

Turns out EventListener is *only* used for FDC3 API events, which only includes the channel changed event currently - adjusting the name (to ApiEventListener? is that any better?) may help with confusion there. You use EventListener to listen for channel changes to apply in DefaultChannelSupport (where it's registered but never removed). Its also used for app channel changed event listeners - so we're missing a test for that. Added one.

File: packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts [hunk 41]
```diff
@@ -1,62 +1,155 @@
...
-  abstract action(m: any): void;
+  action(m: PrivateChannelEventMessages): void {
+    this.handler(m);
+  }
 }
 
-export class PrivateChannelEventListenerVoid extends AbstractPrivateChannelEventListener<() => void> {
-  constructor(messaging: Messaging, channelId: string, handler: () => void) {
-    super(messaging, channelId, 'onDisconnect', handler);
+export class PrivateChannelNullEventListener extends AbstractPrivateChannelEventListener {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts:64]: Added one

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts [hunk 42]
```diff
@@ -1,54 +1,115 @@
...
+    } as Y;
 
-    const response = await this.messaging.exchange<any>(notificationMessage, responseType);
-    return response?.payload?.listenerUUID ?? null;
-  }
+    const response = await this.messaging.exchange<SubscriptionResponse>(subscribeMessage, this.subscribeResponseType);
+    this.id = response?.payload?.listenerUUID ?? null;
 
-  async unsubscribe(): Promise<void> {
     if (!this.id) {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts]: By 'here' do you mean in `register()` or in `unsubscribe()`? I'm going to assume `register()`. 

The problem is that we're integrating with 3rd party code that we don't control. We can totally get here if they send an invalid message that has neither the `listenerUUID` nor `error` properties set in the payload. Yes, we could move to validating all messages as they arrive and throw in exchange, but that will come with a performance hit and we'd need a new error defined in the API to return to the user in every API call. Whereas, with this pattern we're validating just the field we're dependent on and providing feedback to the DA developer (or user who can pass it on to them) about what they did wrong and what will fail because of it. Having spent a lot of time debugging interop code other people wrote, I'm keen on error messages like this - more than I am worried about code coverage for the log line (which is hard to achieve).

File: packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts [hunk 43]
```diff
@@ -66,27 +86,40 @@ export abstract class AbstractUIComponent implements Connectable {
...
       const ml = (e: MessageEvent) => {
-        if (e.source == this.iframe?.contentWindow && e.data.type == BrowserTypes.FDC3_USER_INTERFACE_HELLO_TYPE) {
-          const helloData = e.data as BrowserTypes.Fdc3UserInterfaceHello;
-          if (helloData.payload.initialCSS) {
-            this.themeContainer(helloData.payload.initialCSS);
+        if (e.source == this.iframe?.contentWindow) {
+          if (isFdc3UserInterfaceHello(e.data)) {
+            const helloData = e.data;
+            if (helloData.payload.initialCSS) {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts:104]: WIll do.

File: packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts (hunk 38 above)
[the remark this answers is not in the document]
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts:91]: what about this comment then?

//should never happen as an error returned will be thrown

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:134]: that might be a good approach.   One possible improvement might be to move the validation/throw into the `exchange` function as this is going to be needed a lot

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts (hunk 42 above)
[the remark this answers is not in the document]
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts]: yeah I think we came up with a good approach for this a few comments back - let's use it here too

File: packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts [hunk 44]
```diff
@@ -57,7 +75,9 @@ export abstract class AbstractUIComponent implements Connectable {
   async setupMessagePort(port: MessagePort): Promise<void> {
     port.addEventListener('message', e => {
       const data = e.data;
-      if (data.type == BrowserTypes.FDC3_USER_INTERFACE_RESTYLE_TYPE) {
+
+      if (isFdc3UserInterfaceRestyle(data)) {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts:79]: Yes something is amiss there. It's probably NOT message routing for the iframes in the mocks as this is over the MessagePort. 

The restyle message gets sent here: https://github.com/finos/FDC3/blob/47308875d21927b112d552fedc3a52a85a819735/packages/fdc3-get-agent/test/support/FrameTypes.ts#L83-L95

Will have to track down why its nto getting sent or where its ending up.

File: packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts [hunk 45]
```diff
@@ -66,27 +86,40 @@ export abstract class AbstractUIComponent implements Connectable {
...
+            resolve(port);
+          } else {
+            Logger.debug('AbstractUIComponent: ignored UI Message from UI iframe while awaiting hello: ', e.data);
           }
-          const port = e.ports[0];
-          port.start();
-          globalThis.window.removeEventListener('message', ml);
-          resolve(port);
+        } else {
+          Logger.debug(
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts:115]: Just a log statement on an unexpected case. We could drop the else clause and nothing will break, but it may leave someone with a difficult debug one day - went in while I was have troubl eiwth message routing in the tests.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts (hunk 34 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:121]: Wasn't tested previously:
image

Will add something for it.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts (hunk 36 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts:263]: should be resolved by new test

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts (hunk 42 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts]: 👍

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts (hunk 26 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts:28]: I commented it out and nothing broke except a test line look for the message, which the test after it (different result type) did not. I think it was not needed/added in error... We should confirm

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:134]: I thought about it - but it makes exchange longer and customizing the error/log message is harder there... I've installed that new approach whereever I can so that should cut down on uncovered log lines.

[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:134]: (I'll push that up shortly)

File: packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts (hunk 38 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/apps/DefaultAppSupport.ts:91]: I'll adjust the comment to be clearer - in this case there is no error response to use or error to throw.

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts [hunk 46]
```diff
@@ -24,7 +31,7 @@ export class DefaultIntentListener extends AbstractListener<IntentHandler> {
...
 
   action(m: IntentEvent): void {
-    this.handleIntentResponse(m);
+    //this.handleIntentResponse(m);
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts:34]: Should we just delete this line?

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts [hunk 47]
```diff
@@ -33,23 +40,23 @@ export class DefaultIntentListener extends AbstractListener<IntentHandler> {
...
+  //     },
+  //     payload: {
+  //       intentResolution: {
+  //         intent: m.payload.intent,
+  //         source: this.messaging.getAppIdentifier(),
+  //       },
+  //     },
+  //   };
+  //   this.messaging.post(out);
+  // }
```
Comment (julianna-ciq) [inline packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts:59]: Should we just delete these lines?

File: packages/fdc3-get-agent/test/support/TestServerContext.ts [hunk 48]
```diff
@@ -29,7 +33,7 @@ export class TestServerContext implements ServerContext<ConnectionDetails> {
     this.cw = cw;
   }
 
-  async narrowIntents(_raiser: AppIdentifier, appIntents: AppIntent[], _context: Context): Promise<AppIntent[]> {
+  async narrowIntents(_raiser: AppIdentifier, appIntents: AppIntent[] /*, _context: Context*/): Promise<AppIntent[]> {
```
Comment (julianna-ciq) [inline packages/fdc3-get-agent/test/support/TestServerContext.ts:36]: Should the commented-out argument be deleted?

File: toolbox/fdc3-for-web/demo/src/client/ui/drag.ts [hunk 49]
```diff
@@ -25,7 +25,7 @@ export function dragElement(drag: HTMLElement, selector: HTMLElement, position:
   }
 
   function dragMouseDown(e: MouseEvent) {
-    console.log('astarting');
+    console.log('starting');
```
Comment (julianna-ciq) [inline toolbox/fdc3-for-web/demo/src/client/ui/drag.ts:28]: Should we leave this `console.log` line? If so, can it be a `console.debug`, maybe with a more informative message? Like `console.debug('Channel Selector - DragMouseDown starting')`

File: toolbox/fdc3-for-web/fdc3-web-impl/src/BasicFDC3Server.ts [hunk 50]
```diff
@@ -32,6 +39,7 @@ export class BasicFDC3Server implements FDC3Server {
   }
 
   receive(message: AppRequestMessage | WebConnectionProtocol4ValidateAppIdentity, from: InstanceID): void {
+    // this.sc.log(`MessageReceived: \n ${JSON.stringify(message, null, 2)}`)
```
Comment (julianna-ciq) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/BasicFDC3Server.ts:45]: Should we keep this commented-out line?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts [hunk 51]
```diff
@@ -36,6 +40,8 @@ export class HeartbeatHandler implements MessageHandler {
 
   constructor(pingInterval: number = 1000, disconnectedAfter: number = 5000, deadAfter: number = 20000) {
     this.timerFunction = setInterval(() => {
+      //console.log(`Contexts: ${this.contexts.length} Last Heartbeats: `, this.heartbeatTimes())
```
Comment (julianna-ciq) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:43]: Should this line stay in?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts [hunk 52]
```diff
@@ -95,35 +101,41 @@ export class HeartbeatHandler implements MessageHandler {
...
-      type: 'heartbeatEvent',
-      meta: {
-        timestamp: new Date(),
-        eventUuid: sc.createUUID(),
-      },
-      payload: {},
-    };
-    sc.post(heartbeatEventMessage, app.instanceId!!);
+  async sendHeartbeat(sc: ServerContext<AppRegistration>, app: FullAppIdentifier): Promise<void> {
+    sc.post(
```
Comment (julianna-ciq) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:129]: Could this look like `const event: HeartbeatEvent = { ... }; sc.post(event);`?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts [hunk 53]
```diff
@@ -223,71 +248,86 @@ export class OpenHandler implements MessageHandler {
...
-
-    function returnSuccess(appIdentity: AppIdentifier) {
-      if (!appIdentity.instanceId) {
-        throw new Error("App does not include an instanceId, can't ");
-      }
-      const aopMetadata = _this.filterPublicDetails(
-        _this.directory.retrieveAppsById(appIdentity.appId)[0],
-        appIdentity
+    const returnError = () => {
+      sc.post(
```
Comment (julianna-ciq) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts:305]: Looks like another merge issue

**Review by julianna-ciq — COMMENTED** [review]
Review 101 - 143 / 143

File: packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts (hunk 44 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/ui/AbstractUIComponent.ts:79]: Found it, should have been `isFdc3UserInterfaceHandshake(e.data)` rather than `isFdc3UserInterfaceHandshake(e)`. Code coverage is showing it covered.

File: packages/fdc3-schema/schemas/api/fdc3UserInterfaceHandshake.schema.json [hunk 54]
```diff
@@ -2,7 +2,7 @@
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "https://fdc3.finos.org/schemas/next/api/fdc3UserInterfaceHandshake.schema.json",
   "title": "Fdc3 UserInterface Handshake",
-  "description": "Handshake message sent back to a user interface from the DA proxy code (setup by `getAgent()`) over the `MessagePort` provided in the preceding Fdc3UserInterfaceHello message, confirming that it is listening to the `MessagePort` for further communication.",
+  "description": "Handshake message sent back to a user interface from the DA proxy code (setup by `getAgent()`) over the `MessagePort` provide in the preceding iFrameHello message, confirming that it is listening to the `MessagePort` for further communication.",
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-schema/schemas/api/fdc3UserInterfaceHandshake.schema.json:5]: nope, good spot

File: packages/fdc3-agent-proxy/src/channels/ChannelSupport.ts [hunk 55]
```diff
@@ -2,18 +2,12 @@ import { Channel, ContextHandler, EventHandler, Listener, PrivateChannel } from
 
 export interface ChannelSupport {
   getUserChannel(): Promise<Channel | null>;
-
+  getUserChannel(): Promise<Channel | null>;
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/ChannelSupport.ts:5]: Test have to be the result of a merge (or the rapid onset of senility)

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts (hunk 46 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts]: removed during our meeting earlier (after checking with Rob if it had any relevance)

File: packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts (hunk 47 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/DefaultIntentListener.ts]: ditto

File: packages/fdc3-get-agent/test/support/TestServerContext.ts (hunk 48 above)
Comment (kriswest) [reply packages/fdc3-get-agent/test/support/TestServerContext.ts:36]: Its specified in the interface being implemented, but not used here. I thought it best to leave it in but commented for now.

File: toolbox/fdc3-for-web/demo/src/client/ui/drag.ts (hunk 49 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/demo/src/client/ui/drag.ts:28]: 👍

File: toolbox/fdc3-for-web/fdc3-web-impl/src/BasicFDC3Server.ts (hunk 50 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/BasicFDC3Server.ts:45]: removed

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts (hunk 51 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:43]: removed  - will of course generate endless ticking messages

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts (hunk 52 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/HeartbeatHandler.ts:129]: yup

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts (hunk 53 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/OpenHandler.ts:305]: 👍

File: packages/fdc3-schema/schemas/api/t2sQuicktypeUtil.js [hunk 56]
```diff
@@ -0,0 +1,69 @@
...
+const path = require('path');
+const fs = require('fs');
+const exec = require('child_process').exec;
+
+const args = process.argv.slice(2);
+const outputPath = args.pop();
+const inputs = args;
+
+console.log('Inputs: ' + inputs.join(' | '));
+console.log('Output path argument: ' + outputPath);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-schema/schemas/api/t2sQuicktypeUtil.js:22]: Meh, may kill this file soon - its only showing up in the diff as it was moved.

**Comment by kriswest** [comment]
@robmoffat @julianna-ciq I think I've got all comments and issues resolved or at least responded, so I only have looking at timeouts (on open/raiseIntent etc.) left to do - and that could be a different PR...

Could you check any unresolved comments and see if you're happy or whether you think I need to take it further please.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 37 above)
[the remark this answers is not in the document]
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts]: LGTM

File: packages/fdc3-get-agent/test/support/FrameTypes.ts (hunk 21 above)
Comment (julianna-ciq) [reply packages/fdc3-get-agent/test/support/FrameTypes.ts:75]: Oh well. We can leave it, then.

**Review by julianna-ciq — APPROVED** [review]
lgtm

File: packages/fdc3-agent-proxy/src/util.ts [hunk 57]
```diff
@@ -0,0 +1,20 @@
...
+ *  Used to lightly validate messages being processed primarily to catch errors in Desktop Agent
+ *  implementations.
+ */
+export const throwIfUndefined = (
+  property: object | string | number | null | undefined,
+  absentMessage: string,
+  message: AgentResponseMessage | AgentEventMessage,
+  absentError: ErrorMessages
+): void => {
+  if (property === undefined) {
```
Comment (robmoffat) [inline packages/fdc3-agent-proxy/src/util.ts:16]: can we add a util test for this, like you did with logging?

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 58]
```diff
@@ -1,35 +1,44 @@
...
+  readonly messaging: Messaging;
+  readonly channelSelector: ChannelSelector;
+  protected userChannels: Channel[] = [];
+  protected userChannelListeners: UserChannelContextListener[] = [];
+
+  constructor(messaging: Messaging, channelSelector: ChannelSelector) {
+    this.messaging = messaging;
+    this.channelSelector = channelSelector;
     this.channelSelector.setChannelChangeCallback((channelId: string | null) => {
       if (channelId == null) {
```
Comment (robmoffat) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:43]: still not tested

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts [hunk 59]
```diff
@@ -56,31 +65,37 @@ export class DefaultChannelSupport implements ChannelSupport {
       payload: {},
     };
     const response = await this.messaging.exchange<GetCurrentChannelResponse>(request, 'getCurrentChannelResponse');
-
-    if (response.payload?.channel?.id) {
+    //handle successful responses - errors will already have been thrown by exchange above
+    if (response.payload.channel) {
```
Comment (robmoffat) [inline packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:69]: can't we use your new throwIfUndefined here?

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts [hunk 60]
```diff
@@ -163,26 +169,38 @@ export class DefaultIntentSupport implements IntentSupport {
...
-      messageOut,
+    const resultPromise = this.createResultPromise(request);
+    const response = await this.messaging.exchange<RaiseIntentForContextResponse>(
+      request,
       'raiseIntentForContextResponse',
       ResolveError.IntentDeliveryFailed
     );
+
+    throwIfUndefined(
+      response.payload.error ?? response.payload.appIntents ?? response.payload.intentResolution,
```
Comment (robmoffat) [inline packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:180]: won't get here for a payload error as that will get consumed and thrown by exchange

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts [hunk 61]
```diff
@@ -163,26 +169,38 @@ export class DefaultIntentSupport implements IntentSupport {
...
       }
-    } else {
-      const details = response.payload.intentResolution!;
+    } else if (response.payload.intentResolution) {
+      // Was resolved
+      const details = response.payload.intentResolution;
       return new DefaultIntentResolution(this.messaging, resultPromise, details.source, details.intent);
+    } else {
+      //should never get here as we will throw above
+      throw new Error(response.payload.error);
```
Comment (robmoffat) [inline packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:203]: we can never reach this line, there's something fishy about this

Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:203]: `throwIfUndefined` falls down a bit when we have more than one property.  In this case (and the one above) wouldn't the answer be for this not to be an `else if` but just an `if` and no `else`?  


i.e. logically we know either intentResolution or appIntents is set (because of the `throwIfUndefined`, so just have an if with out else for each.

File: packages/fdc3-get-agent/src/strategies/getAgent.ts [hunk 62]
```diff
@@ -20,87 +38,196 @@ export function getAgentPromise(): Promise<DesktopAgent> | null {
...
+        strategies = [new PostMessageLoader(persistedData.agentUrl)];
+        break;
+      case WebDesktopAgentType.ProxyParent:
+        strategies = [new PostMessageLoader()];
+        break;
+      case WebDesktopAgentType.Failover:
+        strategies = [];
+        break;
+      default:
+        strategies = [new DesktopAgentPreloadLoader(), new PostMessageLoader()];
```
Comment (robmoffat) [inline packages/fdc3-get-agent/src/strategies/getAgent.ts:67]: weirdly, this line isn't covered.  That implies we're not testing multiple strategies at the same time and the race.  We should do.

**Review by robmoffat — CHANGES_REQUESTED** [review]
nearly there!

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts (hunk 60 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:180]: True, someone breaking exchange is hopefully unlikely.

```suggestion
      response.payload.appIntents ?? response.payload.intentResolution,
```

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts (hunk 61 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:203]: If we've got to validate two properties then you just put two `throwIfUndefined` calls. In this case the properties are mutually exclusive so coalescing them in a single test works. We can drop the final else (still needs an else if due to the two different properties).

There's no perf penalty to having the else and it remains defensive (if someone breaks exchange), but we might as well focus on making sure that doesn't happen and go for brevity. Will cut the else.

Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:203]: P.S. added to `exchange` and `waitFor`'s jsDoc to state that they will reject with errors in payloads.

File: packages/fdc3-agent-proxy/src/util.ts (hunk 57 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/util.ts:16]: Sure - we should perhaps do the same for AbstractMessaging's `exchange` and `waitFor` to make sure they continue to throw on errors properly.

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts (hunk 61 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:203]: Ah... Without the else clause typescript can't confirm that all branches return (so it can't be if/elseif ir if/if, it has to be if/else if/else. Putting 'er back.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 59 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:69]: Have put it in and removed the log message, but the else has to stay so that we return on all branches.

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts [hunk 63]
```diff
@@ -128,33 +124,43 @@ export class DefaultIntentSupport implements IntentSupport {
...
-      messageOut,
+    const resultPromise = this.createResultPromise(request);
+    const response = await this.messaging.exchange<RaiseIntentResponse>(
+      request,
       'raiseIntentResponse',
       ResolveError.IntentDeliveryFailed
     );
 
+    throwIfUndefined(
+      response.payload.error ?? response.payload.appIntent ?? response.payload.intentResolution,
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:135]: removed

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts [hunk 64]
```diff
@@ -128,33 +124,43 @@ export class DefaultIntentSupport implements IntentSupport {
...
-    } else {
-      // single intent
-      const details = response.payload.intentResolution!!;
+    } else if (response.payload.intentResolution) {
+      // Was resolved
+      const details = response.payload.intentResolution;
       return new DefaultIntentResolution(this.messaging, resultPromise, details.source, details.intent);
+    } else {
+      //Should never get here as we will throw above
+      throw new Error(response.payload.error);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts:158]: I've refined the comment. We have to do somethign there so that we return on all branches or TYpeScript will error out in build.

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts [hunk 65]
```diff
@@ -1,54 +1,115 @@
...
+    const subscribeMessage: Y = {
+      meta: this.messaging.createMeta() as Y['meta'],
+      payload: this.subscriptionPayload as Y['payload'],
+      type: this.subscribeRequestType as Y['type'],
+    } as Y;
+
+    const response = await this.messaging.exchange<SubscriptionResponse>(subscribeMessage, this.subscribeResponseType);
+    this.id = response?.payload?.listenerUUID ?? null;
+
+    if (!this.id) {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:107]: 👍

**Comment by robmoffat** [comment]
Seeing some new compile errors from a fresh build here:

```

src/intent_resolver.ts:36:65 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

36       data.appIntents.filter(ai => ai.intent.name == e?.target?.value),
                                                                   ~~~~~

src/intent_resolver.ts:37:18 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

37       e?.target?.value,
                    ~~~~~

```

Can you replicate?

File: packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts [hunk 66]
```diff
@@ -1,62 +1,158 @@
...
+  constructor(messaging: Messaging, channelId: string, handler: EventHandler) {
+    const wrappedHandler = (msg: PrivateChannelEventMessages) => {
+      if (isPrivateChannelOnUnsubscribeEvent(msg)) {
+        const event: ApiEvent = {
+          type: 'unsubscribe',
+          details: { contextType: msg.payload.contextType },
+        };
+        handler(event);
+      } else {
+        console.error('PrivateChannelDisconnectEventListener was called for a different message type!', msg);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts:153]: fixed the message - have not added a test, its just single log line. I do want it to create noise if this starts happening (rather than it happening silently) but ideally it never happens.

File: packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts [hunk 67]
```diff
@@ -1,62 +1,158 @@
...
+  constructor(messaging: Messaging, channelId: string, handler: EventHandler) {
+    const wrappedHandler = (msg: PrivateChannelEventMessages) => {
+      if (isPrivateChannelOnAddContextListenerEvent(msg)) {
+        const event: ApiEvent = {
+          type: 'addContextListener',
+          details: { contextType: msg.payload.contextType },
+        };
+        handler(event);
+      } else {
+        console.error('PrivateChannelDisconnectEventListener was called for a different message type!', msg);
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/PrivateChannelEventListener.ts:136]: fixed the message - have not added a test, its just single log line. I do want it to create noise if this starts happening (rather than it happening silently) but ideally it never happens.

File: packages/fdc3-get-agent/src/strategies/HelloHandler.ts [hunk 68]
```diff
@@ -0,0 +1,162 @@
...
+    // create a new one
+    const ifrm = document.createElement('iframe');
+
+    //Wait for the iframe to load... then send it a hello message
+    ifrm.addEventListener('load', () => {
+      if (ifrm.contentWindow) {
+        Logger.debug('Sending hello message to communication iframe');
+        this.sendWCP1Hello(ifrm.contentWindow, '*');
+      } else {
+        Logger.error('iframe does not have a contentWindow, despite firing its load event!');
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/strategies/HelloHandler.ts:90]: Not quite (expects an API response message to be involved), but we could throw - a failure here is likely to interrupt the connection processing anyway. Converted to a throw.

File: packages/fdc3-get-agent/src/strategies/getAgent.ts [hunk 69]
```diff
@@ -20,87 +38,196 @@ export function getAgentPromise(): Promise<DesktopAgent> | null {
 }
 
 function initAgentPromise(options: GetAgentParams): Promise<DesktopAgent> {
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-get-agent/src/strategies/getAgent.ts:40]: I thought both were part of your original design... getAgentPromise is not used anywhere as far as I can see (I thought it was used in tests, apparently not), so killing it off.

**Comment by robmoffat** [comment]
I'm seeing a regression running the conformance tests:

Screenshot 2024-12-19 at 13 38 54

I ran it twice and got the same error both times.  The `fdc3-for-web-impl` branch passes everything, so it's something in this PR.

If you want to replicate locally, you'll need to change this line in `dummy-desktop-agent.ts`:
```
 const directory = new FDC3_2_1_JSONDirectory();
    //await directory.load('/static/da/appd.json');
    await directory.load('/static/da/local-conformance-2_0.v2.json');   // add this
    const sc = new DemoServerContext(socket, directory);
```

And you'll need to run the conformance framework, the branch to use is `2_0_fdc3_for_the_web` and change the package.json local url to wherever you have your FDC3 project checked out:

```
 "dependencies": {
    "@kite9/fdc3-get-agent": "file:../../FDC3/packages/fdc3-get-agent",   // probably needs changing for you
    "buffer": "^6.0.3",
    "chai": "^4.3.6",
    "fdc3_1_2": "npm:@finos/fdc3@^1.2.0",
    "fdc3_2_0": "npm:@finos/fdc3@^2.0.0-beta.4",
```

File: packages/fdc3-get-agent/src/strategies/getAgent.ts (hunk 62 above)
Comment (kriswest) [reply packages/fdc3-get-agent/src/strategies/getAgent.ts:67]: I'll add a note to explain this - this line is only hit if the SessionsStorage has an unexpected/non-standard value in agentType. Using both strategies at once is the default path if there's no data in session storage which happens a couple of lines below.

We can pop a test in for an invalid agentType value to cover it.

Comment (kriswest) [reply packages/fdc3-get-agent/src/strategies/getAgent.ts:67]: Test added

**Comment by kriswest** [comment]
> I'm seeing a regression running the conformance tests:

That is very likely a result of something I've changed as there was quite a lot of work on the private channel lifecycle events. Thanks for the instructions on replicating the test, I'll give it a go and sort that out.

**Comment by kriswest** [comment]
> Seeing some new compile errors from a fresh build here:

I can replicate and will fix, my bad.

However, it demonstrates that the CI checks are not catching build errors in all projects, which we'll need to look at. The check should have failed on this!

**Comment by kriswest** [comment]
> > Seeing some new compile errors from a fresh build here:
> 
> I can replicate and will fix, my bad.

Actually scratch that, according to git blame all thats changed on the typing there is formatting with prettier, its been this way for 6 months. I don't understand why it's failing now... As the CI checks don't pick up the build failure that could have been happening for some time I suppose... If its just started I don't get why.

Regardless, I can fix it by casting to the target type (HTMLOptionElement) so I've done that...

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts (hunk 61 above)
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts]: Ok, let me explain why this is relevant and not cost-free.  As we are measuring code coverage, any time we have code that is less than 100% covered, it adds an overhead to the reviewers (i.e. us).  We have to review the files and see why code coverage isn't complete, and then decide manually whether to accept or reject it.   

My experience is that this adds significant overhead to the review process especially when you have large codebases and regular PRs coming in.  

You can apply this thinking to a lot of my suggestions above.  So, you have to weigh what is going to save us time in the long run - extra effort for reviewing PRs or possibly extra effort debugging.

Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts]: I don't think this is a weakness in typescript, if you've got a branch that doesn't return (implictly returning void) and violates the return type specified that is a legitimate problem - that code wouldn't compile in most languages. The `throwIfUndefined` function we've added (to increase coverage) is part of the issue (in these cases with multiple properties / differnet returns) as typescript is not seeing the test and thrown error it contains, which could eliminate the branch. However, we're in a better state with it. 

Using a type override or similar to eliminate the coverage issue (how it was previously) is probably worse as you've got to parse the code yourself to spot a potential issue, with coverage perhaps providing a false sense of security.

That leaves... an annotation to ignore these else clauses? I've installed one on each one flagged in these reviews. Note they have to go before the if statement to catch the whole else:

```ts
/* istanbul ignore else */
if (response.payload.appIntents) {
  ...
} else if (...) {
  ...
} else {    //ignored
  ...       //ignored
}           //ignored
```

Such things should be used _very_ sparingly!

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 58 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:43]: I believe this to be the main point outstanding (timeouts and debug logging to go in other PRs) - will ping when I have it solved.

Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:43]: Well this and having a CI check fail if one of the builds fails - are you able to look at that @robmoffat?

File: packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts (hunk 61 above)
Comment (robmoffat) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts]: > I don't think this is a weakness in typescript,  

So we know from this line that either appIntents or intentResolution is set:

```
throwIfUndefined(
      response.payload.error ?? response.payload.appIntent ?? response.payload.intentResolution,
      'Invalid response from Desktop Agent to raiseIntent!',
      response,
      ResolveError.NoAppsFound
    )
```

Therefore if this isn't true:

```
 if (response.payload.appIntent) {
      // Needs further resolution, we need to invoke the resolver
  ...
```

Then intentResolution must be set, so you can do:

```
 } else {
      // Was resolved
      const details = response.payload.intentResolution!;
      return new DefaultIntentResolution(this.messaging, resultPromise, details.source, details.intent);
    }
```

There are good uses for `!` - the typescript type system can't do everything, including this case where one of two things is definitely set. It just models that as both are optional.

Comment (kriswest) [reply packages/fdc3-agent-proxy/src/intents/DefaultIntentSupport.ts]: Fair enough, given that the original issue is solved either way (validating the DA's response) we can go with whats shorter!

File: packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts (hunk 58 above)
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:43]: This is untested in the base branch. I think thats because this code has to be called by the fdc3-get-agent package and is exercised in the fdc3-get-agent tests. To test it here we'll need an additional mock for the channel selector - working that up.

Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannelSupport.ts:44]: Added the test for this

File: toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts [hunk 70]
```diff
@@ -10,20 +10,41 @@ enum Opener {
...
 }
 
-type DemoRegistration = AppRegistration & {
+type DemoAppRegistration = AppRegistration & {
   window: Window;
   url: string;
 };
 
-//Typeguard used to check if application launch details have a URL
+type DemoLaunchRegistration = AppRegistration & {
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts:18]: Let's have a chat about this.  I don't really understand why you're going through all this.  Wouldn't it be just better to register the window promise and use that?  After all, the promise is just a container... you can pull the window out of it at any time.

**Review by robmoffat — CHANGES_REQUESTED** [review]
This is really close - just a couple of things to look at, might be best if we have a call because it's kind of confusing what's going on.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts [hunk 71]
```diff
@@ -68,11 +71,38 @@ export class BroadcastHandler implements MessageHandler {
 
   shutdown(): void {}
 
-  getCurrentChannel(from: AppIdentifier): ChannelState | null {
-    // instanceId is optional
-    if (!from.instanceId) {
-      return null;
-    }
+  cleanup(instanceId: InstanceID, sc: ServerContext<AppRegistration>): void {
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: we need to test this

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts [hunk 72]
```diff
@@ -116,16 +125,29 @@ class PendingIntent {
...
     this.timeoutMs = timeoutMs;
   }
 
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  cleanup(instanceId: InstanceID, _sc: ServerContext<AppRegistration>): void {
+    this.registrations = this.registrations.filter(reg => reg.instanceId != instanceId);
+    //don't clean up pendingIntents as some apps may load
+
+    //cleanup pendingResolutions
+    this.pendingResolutions.forEach((val, key) => {
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:144]: this needs a test

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts [hunk 73]
```diff
@@ -502,20 +545,33 @@ export class IntentHandler implements MessageHandler {
...
   }
 
   async findIntentsByContextRequest(
     r: FindIntentsByContextRequest,
     sc: ServerContext<AppRegistration>,
-    from: AppIdentifier
+    from: FullAppIdentifier
   ): Promise<void> {
     // TODO: Add result type
     const { context } = r.payload;
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:577]: some coverage missing in this function - you might want to investigate

**Comment by robmoffat** [comment]
Ok, I'm just running some of the demo apps and I'm seeing an issue.  App1 connects to and broadcasts on the red channel, but the channel selector stays grey (i.e. no channel)

Screenshot 2025-01-08 at 11 39 12

**Comment by robmoffat** [comment]
... and the intent resolver no longer appears either for the gui demos.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts [hunk 74]
```diff
@@ -56,6 +56,7 @@ export class DefaultChannel implements Channel {
     let theContextType: string | null;
     let theHandler: ContextHandler;
 
+    /* istanbul ignore else */
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:59]: There's no standard behaviour to test here - there is no error defined for this case. Any test we put in will be enforcing arbitrary behaviour so I didn't see any value in either tracking or testing it until we sort that out.

We did create an error for `MalformedContext` in 2.1, but ahve never had one for passing invalid arguments to a function. Its probably time we fixed that... although not in this PR.

[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:59]: Created an issue for 2.3 to plug that gap: https://github.com/finos/FDC3/issues/1490

I'll see if I can drop in a test to just check it throws an error, we then check the error message when a standard one exists.

File: packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts [hunk 75]
```diff
@@ -78,6 +80,7 @@ export abstract class AbstractListener<X, Y extends SubscriptionRequest> impleme
   abstract action(m: AgentEventMessage): void;
 
   async unsubscribe(): Promise<void> {
+    /* istanbul ignore else */
```
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/listeners/AbstractListener.ts:83]: Yes on this one, it's a defensive `else` clause that will give a meaningful error if someone breaks the implementation. For now it's not possible to reach but a better option than a non-null assertion IMHO.

**Comment by robmoffat** [comment]
conformance tests all passing for me!

File: toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts [hunk 76]
```diff
@@ -47,17 +47,30 @@ export interface ServerContext<X extends AppRegistration> {
...
+   * an app and when validating an app's identity when connecting.
    */
   getInstanceDetails(uuid: InstanceID): X | undefined;
 
+  /**
+   * Returns the connection details for a particular instance of an app that
+   * was previously connected to the Desktop Agent. Used when validating an
+   * app's identity when reconnecting.
+   */
+  getPastInstanceDetails(uuid: InstanceID): X | undefined;
```
[the remark this answers is not in the document]
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts:72]: When I found the issue I addressed with this, the state for the app was already gone - I couldn't quite figure out why. Possibly some issue in `setInstanceDetails` (which replaces the connections array in a few places). That's why I asked you to check this as I couldn't discern what you actually intended to happen with disconnects, only that it wasn't working and was blocking reconnection (on even a simple refresh). It may be that I have corrected whatever was deleting the state of terminated apps - I guess we'll find out if I remove the explicit removal in the goodbye function below. I have definitely altered things so that apps are not blocked from re-connecting if their state is gone but we'll need to make sure they can reclaim it if its still there...

We should try and describe the architecture and role of different components before we finish up here - without at least minimal docs this will be hard to maintain - I've had to read a lot of code to understand behavior and in this case I couldn't discern how it was intended to work.

Using the app state should work... but nothing has been rigged up to clean-up state based on it. When an app is terminated its context handlers etc. need cleaning up, so we definitely need some of whats been added to the server context and FDC3Server - more in the next comment.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts [hunk 77]
```diff
@@ -47,17 +47,30 @@ export interface ServerContext<X extends AppRegistration> {
    */
   open(appId: string): Promise<InstanceID>;
 
+  /**
+   * Handle clean-up of state after an app instance disconnects.
+   */
+  goodbye(instanceId: string): void;
```
[the remark this answers is not in the document]
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts:53]: The heartbeatHandler is in charge of goodbye messages and timeouts, so yes should probably call this - or what it does should be moved into setAppState. The tests don't exercise heartbeat disconnections well AFAIK.

However, this function already existed in your DemoServerContext (see fdc3-for-web-impl @ https://github.com/finos/FDC3/blob/fb996b1638edbc2d3e3c061437c473150a328d11/toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts#L76C6-L83) and is being called on socket disconnections - that must be what has been deleting the connection state and breaking reconnection/use of the appState. I added the function to the ServerContext interface and then altered the implementation to move the details to pastConnections rather than just deleting. I also changed it up so that it calls cleanup on the FDC3Server, which in turn calls `goodbye` on the serverContext after cleaning up its own state for context listeners etc. - that is definitely needed (context doesn't have a reference to the server so it haas to be that way round).

We can lose pastConnections and work with the app state, but socket connection in your demo implementation also needs to do so I guess.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts [hunk 78]
```diff
@@ -135,6 +135,19 @@ export class IntentHandler implements MessageHandler {
     this.timeoutMs = timeoutMs;
   }
 
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```
[the remark this answers is not in the document]
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:138]: nope eslint still flags it. Apparently the _ syntax is dated an current thinking is that we should remove unused variables, so the linting tools flag regardless of an _ prefix.

Elsewhere, I've commented the unused arg out. I think either the explicit rule disable or leaving the commented argument in is better/clearer for future developers than just dropping it when it exists on the interface. Either is more explicit that we just didn't need to use it in this specific implementation.

File: toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts (hunk 70 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts:18]: Its so we can check fully realized windows first before waiting on anything to be realized.  That matters in `getInstanceForWindow` where you are comparing window objects, we want to compare to all realized windows first in the hopes its one of those, before starting to wait on unrealized windows - as we'll have to wait on all of them as we don't know which one it will turn out to be. Differentiating them isn't hard if you switch their type as they get realized.

What makes it difficult is that its not possible to tell if a promise is resolved without waiting on it - theres no status field. There is an alternative workaround based on wrapping the promise, creating a state field, waiting on the promise and setting it internally but that adds as much complexity and additional typing. The typeguards are easy enough to read in code later.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts (hunk 71 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: Yes, cleanup was not being performed prior to this (when reconnect was fixed, it generated an additional copy of each broadcast or intent event for each reconnection). I guess that's a case of checking outgoing messages are correct after a reconnect and over multiple broadcasts (the last message will be correct, but need to check it wasn't duplicated - so need to look back through more messages)?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 72 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:144]: I don't see how we can test that meaningfully - other than by inspecting the state? Answers on a postcard.

File: packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts (hunk 74 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply packages/fdc3-agent-proxy/src/channels/DefaultChannel.ts:59]: Test added and passing, will push later on

File: toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts (hunk 70 above)
Comment (robmoffat) [reply toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts:18]: ok... but what's wrong with just waiting on the window promise?  That sorts out the race, doesn't it?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts (hunk 71 above)
Comment (robmoffat) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: You'll need to make some changes to `TestServerContext` for that - at the moment, it won't send messages to destinations that have disconnected.  But if you changed it so that it sent to some dead-letter address you could add those messages to the `postedMessages` list and check them in the test.

File: toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts (hunk 70 above)
Comment (robmoffat) [reply toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts:18]: unfortunately, I'm not going to be able to test this on my own machine, but I feel like the problem was that `window.open` was synchronous and slow, and so this call wasn't completing in time for the `getInstanceDetails(uuid: InstanceID)` call to find it.   Just changing to a promise should fix this on it's own.   Unless there are some other issues I can't ascertain from the code?

Anyway, this is just a demo so I'm happy to let it slide, it's just from my  possibly incomplete understanding of the problem this seems over-complex.

Comment (kriswest) [reply toolbox/fdc3-for-web/demo/src/client/da/DemoServerContext.ts:18]: window.open was actually fine (at least in my tests), it returns a window object synchronously which can be compared with other window proxy objects. It was iframes that were the problem, as you have to wait for them to load before they have a `contentWindow` you can return as the window proxy. That puts you into a place where the connection is happening at the same time as the windowProxy is being returned and the uuid recorded. It's inherently a race between different render threads (not something you have to deal with in JavaScript until you are dealing with multiple windows/browsing contexts/render threads.

I've adjusted the type names and guards just now to make things a little clearer. They are there to make things more readable. 

Anyway I think this is working - only using promises might make the code a hair shorter, but I believe has some additional pitfalls (basically needing to race every promise every time you are looking for a window object) that its probably not worth exploring right now. The main thing is that it appears to be working consistently now.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts (hunk 71 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: The important thing is that it has disconnected then reconnected, but state got cleaned up in between. Hence the challenge is simulating the disconnection - I think just calling the cleanup function on the server for the UUID, then registering again _should_ do that....

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 72 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:144]: SHould be able to do it based on postedMessages again - I just noted that you currently send an error response if the pendingResolution doesn't exist - I'm changing that to return a success response and just not send on the result (as the app that raised the intent has gone away). That makes the test possible by checking that a `raiseIntentResultResponse` was NOT sent if the app had disconnected.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts (hunk 71 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: It does, have manually broken it to make sure the test will catch a lack of cleanup and it appears to.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 72 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:144]: Done that, which covers it.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 73 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:577]: ug, theres more than an uncovered line to sort here - the tests don't cover multiple results for findIntentsByContext and are not picking up the fact that every app with an intent registered is being returned here (filtering is not working). Also running apps are not returned.

Will have a go at fixing it

Comment (robmoffat) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:577]: running apps were returned in the past, fwiw

Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:577]: only in findIntent, looks like it was missing in findIntentForContext.

Incidentally on findIntent it looks like, if there are instances running, it only returns those and not the the record with just the appId (indicating launch a new instance). I'll confirm that and adjust the tests if thats the case - if it is the case we must be missing that in the conformance tests...

File: toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts (hunk 77 above)
[the remark this answers is not in the document]
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts]: This is fixed. I did have to link the ServerContext to its server to do so as if the termination comes from the ServerContext it needs to tell the server and handlers, if it comes from the heartBeat handler, then that needs to tell the ServerContext. Its not my favourite but I think it forced by separating the handlers and ServerContext into separate units.

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts (hunk 71 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/BroadcastHandler.ts:74]: Added testing

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 72 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts:143]: Added testing for this

File: toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts (hunk 73 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/handlers/IntentHandler.ts]: fixed both findIntent and findIntentForContext and added tests

**Comment by kriswest** [comment]
@robmoffat the UIs are fixed - they needed some work on timing and I found a couple of the old iframe messages (that we replaced with Fdc3UserInterface) in the demo implementations. I was able to complete the intent resolver manual test cases in the conformance framework and the channel selector is populated again and responds to channel changes via the API.

Ready for another look.

File: packages/fdc3-get-agent/src/util/Picocolors.ts [hunk 79]
```diff
@@ -0,0 +1,114 @@
+/* 
+From picocolors (imported due to issues building in both ESM and CommonJS) 
+https://github.com/alexeyraspopov/picocolors
+
+ISC License
```
Comment (robmoffat) [inline packages/fdc3-get-agent/src/util/Picocolors.ts:5]: I'm a bit worried about this license.  A lot of FDC3's users have automated tools for license scanning and approvals.   If FDC3 suddenly ends up being mixed-license (Apache + ISC) then it may get flagged.  

According to opensource.org https://opensource.org/license/isc-license-txt. this license is currently not categorised as open source.  Is there an alternative with an Apache license we can use?

File: packages/testing/src/steps/generic.steps.ts [hunk 80]
```diff
@@ -161,6 +161,10 @@ export function setupGenericSteps() {
     expect(handleResolve(field, this)['message']).toBe(errorType);
   });
 
+  Then('{string} is an error', function (this: PropsWorld, field: string) {
+    expect(handleResolve(field, this)).toBeInstanceOf(Error);
```
Comment (robmoffat) [inline packages/testing/src/steps/generic.steps.ts:165]: Why not use the existing 'error with message' and assert that the error matches "Invalid arguments passed to addContextListener!"?

File: toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts [hunk 81]
```diff
@@ -36,21 +37,18 @@ export interface ServerContext<X extends AppRegistration> {
...
 
-  /**
-   * Handle clean-up of state after an app instance disconnects.
+  /** Set the FDC3Server instance associated with this context. This reference is
+   *  used to notify the server to cleanup state for apps that have been terminated.
+   *  The FDC3Server is passed a ServerContext when created and should call this fn
+   *  in its constructor.
    */
-  goodbye(instanceId: string): void;
+  setFDC3Server(server: FDC3Server): void;
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts:51]: rather than introduce the FDC3Server here, it might be better to have cleanup involve just the ServerContext and MessageHandler classes.   setAppState() on the ServerContext can then chain cleanup on the MessageHandlers if it wants to.

File: toolbox/fdc3-for-web/reference-ui/src/main.ts [hunk 82]
```diff
@@ -128,7 +128,7 @@ const openChannelIframe = (e: MouseEvent) => {
   const channel = new MessageChannel();
 
   // STEP 2B: Receive confirmation over port from iframe
-  channel.port1.onmessage = ({ data }) => {
+  channel.port1.addEventListener('message', ({ data }) => {
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/reference-ui/src/main.ts:131]: Have you tested this code?  I can't get it to run.  If you can't either I suggest we take it out and the index.html file - people will be able to test the channel selector and intent resolver much better through the demo.

**Review by robmoffat — CHANGES_REQUESTED** [review]
Couple of minor issues.  The only one stopping me hitting approve is the license for pico colours really.  Perhaps you can just add the ANSI codes directly into your logger and remove the dependency entirely?

I'm going to do some testing now.

**Comment by robmoffat** [comment]
`dummy-desktop-agent.ts`:
```
 //await directory.load('/static/da/appd.json');
    await directory.load('/static/da/local-conformance-2_0.v2.json');
```

This is pointing to conformance where really it should be the local appd line (reverse the commenting)

**Comment by robmoffat** [comment]
Ok, one more UI thing, the default channel appears to be white now, instead of black.  But that makes it hard to see against the workbench:

Screenshot 2025-01-13 at 10 50 12

Screenshot 2025-01-13 at 10 49 59

Obviously, if workbench was running in dark mode, the reverse would be true!

**Comment by kriswest** [comment]
> Ok, one more UI thing, the default channel appears to be white now, instead of black. But that makes it hard to see against the workbench:

...

> Obviously, if workbench was running in dark mode, the reverse would be true! We might want to consider adding a white background to the channel icon?

I don't think I changed anything there. Seems like a design issue if it doesn't display against a white background.  That should probably be addressed (not sure thats within the scope of this PR, despite how sprawling it has become). 

We should perhaps switch to the recommended channel set anyway...

**Comment by kriswest** [comment]
> This is pointing to conformance where really it should be the local appd line (reverse the commenting)

Fixing that.

File: packages/fdc3-get-agent/src/util/Picocolors.ts (hunk 79 above)
Comment (kriswest) [reply packages/fdc3-get-agent/src/util/Picocolors.ts:5]: I intend to remove it and replace with a custom implementation - this was a result of my frustration at not finding a lib for this that would build under both es6 and commonjs. I was going to do that in the debug logs PR...

File: packages/testing/src/steps/generic.steps.ts (hunk 80 above)
Comment (kriswest) [reply packages/testing/src/steps/generic.steps.ts:165]: Because the error message is non-standardized. There doesn't seem any point in enforcing the arbitrary message. Instead I'd rather pursue this in 2.3 and then do it properly:
- #1490

**Comment by robmoffat** [comment]
Conformance tests all passing for me. 🥳

File: toolbox/fdc3-for-web/reference-ui/src/main.ts (hunk 82 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/reference-ui/src/main.ts:131]: It looked well out of date to me and out of sync with the UI implementations, I fixed a few things but not tested - it definitely needs work to run.

@julianna-ciq

File: packages/testing/src/steps/generic.steps.ts (hunk 80 above)
Comment (kriswest) [reply packages/testing/src/steps/generic.steps.ts:165]: WIll add a comment to the test and code regarding that.

File: packages/fdc3-get-agent/src/util/Picocolors.ts (hunk 79 above)
Comment (kriswest) [reply packages/fdc3-get-agent/src/util/Picocolors.ts:5]: Actually, it is an OpenSource license, approved by the Open Source Initiative - the categorizations they display are within the set of Open Source licenses and are:
image
Its also the default license on NPM packages created with `npm init` (I'm told).

Regardless I intend to replace this with a cusotm implementation.

File: packages/testing/src/steps/generic.steps.ts (hunk 80 above)
Comment (kriswest) [reply packages/testing/src/steps/generic.steps.ts:165]: done

**Comment by kriswest** [comment]
@robmoffat regarding the channel selector UI, there aren't white of black channels... The demo implementation is working fine for me. However, if I select the 'Default Web FDC3' UI in the demo I don't see the selector at all. Likely something needs fixing there - no idea why its even halfway working for you. Did you rebuild everything?

**Comment by kriswest** [comment]
> @robmoffat regarding the channel selector UI, there aren't white of black channels... The demo implementation is working fine for me. However, if I select the 'Default Web FDC3' UI in the demo I don't see the selector at all. Likely something needs fixing there - no idea why its even halfway working for you. Did you rebuild everything?

Oh you have to start the server for the reference UI separately... Still no white or black channels however. Also neither UI seems to allow deselecting the channel, which seems a flaw.

**Comment by robmoffat** [comment]
> Oh you have to start the server for the reference UI separately... 

Yes I did this but it still seemed a bit non-functional.  

Still no white or black channels however. 

 > Also neither UI seems to allow deselecting the channel, which seems a flaw.

Agreed

File: toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts (hunk 81 above)
Comment (robmoffat) [reply toolbox/fdc3-for-web/fdc3-web-impl/src/ServerContext.ts:51]: yes, I agree about the problem.  This is as a result of cleanup needing to work across all the handlers.  The `ServerContext` is separated out from the handler as it's expected that an implementation of the Desktop agent Server (in this case, `demo`), will want to implement that in it's own way.  Whereas the behaviour of opening / resolving intents etc.  will be reused.

> If you don't want the ServerContext linked back to the server, then it will need to be linked to all the handlers so it can notify them to clean up their state (which is all that link is for) - that may be worse...

I think it would be less bad to have two classes referencing each other than three.  But if you don't think this would be an improvement then just leave it.

File: packages/fdc3-get-agent/src/util/Picocolors.ts (hunk 79 above)
Comment (robmoffat) [reply packages/fdc3-get-agent/src/util/Picocolors.ts:5]: ok great. Yes, I misunderstood that.

**Comment by kriswest** [comment]
> That part worked for me. The bit that didn't work so well that I drew attention to in my review is the index.html page in this ui-reference project, which doesn't really do anything, and the main.ts file that it uses.

I believe the purpose was testing outside of the DA, not sure when it fell behind.

> Still no white or black channels however.

Ah you mean when no channel is selected! I'll work on making it possible to deselect the channel first then have a think, we probably need styling that will work on either black or white... perhpas a white stroke on the cube + a drop shadow?

**Comment by robmoffat** [comment]
> Ah you mean when no channel is selected! I'll work on making it possible to deselect the channel first then have a think, we probably need styling that will work on either black or white... perhpas a white stroke on the cube + a drop shadow?

Yes, sorry.   It's clear in the demo's own implementation but not visible in the reference-ui version.

**Comment by kriswest** [comment]
It wasn't possible to deselect the channel in either implementation, I've fixed that as well as text contrast on each item:

Demo:
image

Default:
image


And have tried to bodge the logo styles on the default implementation to be visible on any backdrop:

image
image
image

Although it may be better to use the color contrast function I added for the text colours to flip the stroke color to black when white doesn't contrast with the colour... That'll need a little tuning of the SVG to look right.

File: packages/fdc3-get-agent/src/util/Picocolors.ts (hunk 79 above)
Comment (kriswest) [reply packages/fdc3-get-agent/src/util/Picocolors.ts]: picocolors removed / replaced

File: toolbox/fdc3-for-web/demo/src/client/da/dummy-desktop-agent.ts [hunk 83]
```diff
@@ -55,18 +55,98 @@ window.addEventListener('load', () => {
...
-        id: 'three',
+        id: 'fdc3.channel.1',
         type: ChannelType.user,
         context: [],
-        displayMetadata: { name: 'THE GREEN CHANNEL', color: 'green' },
+        displayMetadata: {
+          name: 'Channel 1',
+          color: 'red',
+          glyph: '1',
+          glyphColor: 'white',
```
Comment (robmoffat) [inline toolbox/fdc3-for-web/demo/src/client/da/dummy-desktop-agent.ts:71]: I'm getting a compile error here, which I can fix by changing to this:

```
export type ChannelState = {
  id: string;
  type: ChannelType;
  context: Context[];
  displayMetadata: DisplayMetadata & { glyphColor: string };
};
```

in BroadcastHandler 

but is that just me?

Comment (robmoffat) [reply toolbox/fdc3-for-web/demo/src/client/da/dummy-desktop-agent.ts:71]: ... but actually I don't think you're even using `glyphColor`!

**Review by robmoffat — APPROVED** [review]
Thumbs up from me.. although there's one issue you can look at

File: toolbox/fdc3-for-web/demo/src/client/da/dummy-desktop-agent.ts (hunk 83 above)
Comment (kriswest) [reply toolbox/fdc3-for-web/demo/src/client/da/dummy-desktop-agent.ts]: Gah, you're right. That was an abortive attempt to fix color contrast on channels - before I went and did it properly with a luminance based contrast calculation. Removed it. Getting no build errors this end.

**Review by robmoffat — APPROVED** [review]
